apiVersion: apps/v1
kind: Deployment
metadata:
  name: namegen-app
  labels:
    app: namegen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: namegen
  template:
    metadata:
      labels:
        app: namegen
    spec:
      containers:
      - name: namegen
        image: public.ecr.aws/k5u0o7b3/majd-namegen:latest
        ports:
        - containerPort: 8080
