name: Build and Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Source code
      run: cd namegen

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4

      with:
        aws-access-key-id: ${{ secrets.Access_key }}
        aws-secret-access-key: ${{ secrets.Secret_access_key }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Docker image
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k5u0o7b3
        docker build -t majd-namegen ./namegen
        docker tag majd-namegen:latest public.ecr.aws/k5u0o7b3/majd-namegen:latest
        docker push public.ecr.aws/k5u0o7b3/majd-namegen:latest

    - name: Deploy to EKS
      run: |
        aws eks --region eu-central-1 update-kubeconfig --name project-cluster
        kubectl apply -f k8s_manifests/app_deployment.yaml --validate=false
        kubectl apply -f k8s_manifests/app_svc.yaml --validate=false
        kubectl rollout status deployment/namegen-app
        kubectl get svc namegen-service -o wide
